### PR TITLE
TEIIDSB-170

### PR DESCRIPTION
**Pull request by rareddy**

### CODE REVIEW

**Comment by shawkins** [comment]
Looks good.  I'd do some tweaks of the schema manipulation logic: https://github.com/shawkins/teiid-spring-boot/commit/84e137e6c1f10f3f3ed4d05baa3ad4d3ba18734e

I can submit it as a pr, or just check it in after you commit this.

- change materialized back to hidden, which I'll address the resolving issues for
- reuse the schema that is created by the metadata factory
- use serialization utils for cloning
- use the full name of the materialized view as you could have conflicts from multiple schemas

I would give more thought to making the target schema name is unique.  It's easy to check the local schema list - it only gets more complicated if there are vdb imports, which frankly I'm not sure exactly how we're handling those as we move more towards the crd only scenario.

**Comment by rareddy** [comment]
Thanks. You can apply your changes on top, I reviewed them look good. I did not know about the `SerializationUtils` class before.

**Comment by rareddy** [comment]
>I would give more thought to making the target schema name is unique. It's easy to check the local >schema list - 

Right now the Database class throws the DuplicateSchemaException if the name collision occurs

>it only gets more complicated if there are vdb imports, which frankly I'm not sure exactly how we're >handling those as we move more towards the crd only scenario.

We have not yet said we will get away from the Maven-based VDBs, if the Schema Registry-based VDBs is any fruitful then we can consider removing it.

**Comment by shawkins** [comment]
> Right now the Database class throws the DuplicateSchemaException if the name collision occurs

I know that, but it's pretty issue to assign a unique name - you could even use a uuid as there's no user facing need to have a simple name.

> We have not yet said we will get away from the Maven-based VDBs, if the Schema Registry-based VDBs is any fruitful then we can consider removing it.

I know we haven't yet.  To clarify I'm saying a couple of things.  As the focus moves to crd - especially with embedded ddl how is that importable?  Also the existing maven scenario as currently defined it's just the ddl - without any of the runtime characteristics (which were included in the previous incarnation of import) - so every importing vdb must redefine all of the source connectivity, udf dependencies, etc.

**Pull request merged**
