### PR TITLE
Fix unit test due to reordering of metadadta

### PR DESCRIPTION
**Pull request by vhalbert**

### CODE REVIEW

**Comment by vhalbert** [comment]
Closing this request as it appears there is something that causes the ordering to be different when built locally.  I'll work around the issue so that I can move on.

**Comment by shawkins** [comment]
If you are able to create that version of results, then this will probably need to be looked at as it's implying the usage of an undefined hashmap order that could vary by jre.

**Comment by vhalbert** [comment]
I'm seeing this failure in both jdk 8 and 11:
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK Runtime Environment Zulu11.33+15-CA (build 11.0.4+11-LTS)

**Comment by shawkins** [comment]
Probably a mac vs. linux issue.  There is a Files.walk call to get the ddl files - https://stackoverflow.com/questions/10396649/order-of-traversal-in-files-walkfiletree

Seems like we should merge in the order of the import statements for consistency.

**Comment by vhalbert** [comment]
I'm running fedora 30

**Comment by shawkins** [comment]
regardless Files.walk introduces the potential for an undefined ordering - if it's not mac vs. linux, then we'd have to look at the filesystem, etc.  In any event we can address that by processing the imports in the order defined in the vdb.

**Comment by rareddy** [comment]
Iis that going to be in core Teiid?

**Comment by shawkins** [comment]
The Files.walk is in the teiid-spring-boot VdbMojo: https://github.com/teiid/teiid-spring-boot/blob/80fe07794756f753e695b5617a5036f501aee88a/tools/vdb-plugin/src/main/java/org/teiid/maven/VdbMojo.java#L111

The order that it finds files will determine what order things appear in the resultant ddl.  It would be nice to just order things by the imports in the vdb, but the code isn't really setup for that.  So the simplest change would be to sort the files:

.filter(f -> f.endsWith("-vdb.ddl")).sorted().collect(Collectors.toList());

**Pull request closed without merging**
