### PR TITLE
TEIIDSB-41: Removing eclipse based dependencies from hibernate-tools.…

### PR DESCRIPTION
**Pull request by rareddy**
…jar. Also turning on the dependency check plugins and fixing the errors pointed out

### CODE REVIEW

**Comment by shawkins** [comment]
Looks great.  This and the teiid changes reduced the rdbms example jar by 40%.

It looks like travis builds were not active for this repo, so that has been enabled now too.  Let me know if you don't want that.

**Comment by rareddy** [comment]
Do you mean for the openshift-examples repo? originally I did not even want to have a build there, this should be more docs like with example IMO. For spring boot I have travis, but looks like I did that from my account instead of using Teiid account, I have been planning to move to Teiid account but forgot.

**Comment by shawkins** [comment]
> Do you mean for the openshift-examples repo?

No, tsb

> For spring boot I have travis, but looks like I did that from my account instead of using Teiid account, I have been planning to move to Teiid account but forgot.

It's no enabled under teiid as well.

**Comment by rareddy** [comment]
I will delete the job under my name now. thanks.

**Pull request merged**
