### PR TITLE
cassandra support to spring boot

### PR DESCRIPTION
**Pull request by aditya300899**
I think this is just a basic implementation of what I'm supposed to this with this feature. Kindly see and let me know what more things are to be done to get this right.

### CODE REVIEW

**Comment by shawkins** [comment]
This looks good.  The only addition would be to put spring data cassandra as a managed dependency in the root pom - that pom acts as a bom for projects that use Teiid Spring Boot.

**Comment by aditya300899** [comment]
I am facing a few issues with the build due to dependency conflicts. 
When building on local this error comes:
Found a problem with the dependency org.ow2.asm:asm
  Resolved version is 5.0.3
  Version 5.0.3 was expected by artifact: org.teiid.connectors:translator-cassandra
  Version 5.0.4 was expected by artifact: org.springframework.boot:spring-boot-starter-test

Version can't be updated in teiid since this is a compiled dependency for dependency "com.datastax.cassandra:cassandra-driver-core" that uses the 5.0.3 version in all it's versions. I tried out override but then there were dependency conflicts in another module spring-rdbms-example for the dependency org.hibernate:hibernate-core.. 
The solution that works is:
to make the version of org.ow2.asm:asm as 7.1 or greater
and to change the version of org.hibernate:hibernate-core to 5.4.12.Final

Shall I do these changes or something else needs to be done?

And one more doubt: The build is failing for upstream teiid-spring-boot, it is showing dependency conflicts for the module spring-data-soap.

**Comment by shawkins** [comment]
The hibernate dependency did need to be updated for the alignment to spring boot 2.2.6.  That and some additional clean up was checked in with https://github.com/teiid/teiid-spring-boot/commit/4edcb00a3fed212a17ea178c36775814fe92deec

On asm, in your cassandra or the root pom you can add:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>5.0.4</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

That will force json path and cassandra to use the same transitive version.  I wouldn't go all the up to 7.1 as that's quite a version jump.

**Comment by aditya300899** [comment]
When I tried the version change  to 5.0.4 previously in the same fashion as you suggested it was conflicting with some other module's  org.ow2.asm:asm where the required version was 7.1(not exactly sure  but it was in the line of 7). I am facing internet problems right now thus can't tell the exact module. 

Also, what about this?

This was the error that popped up with the spring-data-soap module:
 
Found a problem with the dependency javax.xml.soap:javax.xml.soap-api
  Resolved version is 1.4.0
  Version 1.4.0-b01 was expected by artifact: org.teiid.wildfly.connectors:ws-cxf

**Comment by shawkins** [comment]
> Found a problem with the dependency javax.xml.soap:javax.xml.soap-api

Teiid master ws-cxf should no longer use javax.xml.soap.  That was changed to jakarta.xml.soap-api via the jakarta.xml.ws-api dependency.  If you don't have a local build of Teiid that may mean the snapshot needs updated again.

**Comment by shawkins** [comment]
Good work.  If you are up for it the next task is to allow cassandra to be used by the Teiid operator - https://issues.redhat.com/browse/TEIIDSB-201

**Comment by aditya300899** [comment]
Yes, I'm up for it!  Is the teiid  operator gonna run fine on an 8GB RAM laptop?

**Comment by shawkins** [comment]
> Yes, I'm up for it! Is the teiid operator gonna run fine on an 8GB RAM laptop?

Unfortunately probably not.  But you should be able to at least build it.

**Comment by aditya300899** [comment]
Okay I'll get the RAM increased in the coming days asap. Meanwhile I'll build this and see what needs to be done in this task. Also I haven't worked on GO before so I'll dedicate my time to learn stuff. Thank you!!

**Comment by rareddy** [comment]
No need @aditya300899 to increase RAM or leaning Go for this task. Increased RAM can get you with OpenShift installed that itself can be useful separately. Note that to run OpenShift locally without issues you may need more than 16GB. GO is not required to put together a small YAML file. However if you want to help out with Operator development then yes you do need to know. For this issue all you need is just a modified version of a file like this https://github.com/teiid/teiid-operator/blob/master/deploy/crs/vdb_from_mongodb.yaml for Cassandra. Then you can consider a blog of using Teiid or Teiid Spring Boot.

**Comment by aditya300899** [comment]
> No need @aditya300899 to increase RAM or leaning Go for this task. Increased RAM can get you with OpenShift installed that itself can be useful separately. Note that to run OpenShift locally without issues you may need more than 16GB. GO is not required to put together a small YAML file. However if you want to help out with Operator development then yes you do need to know. For this issue all you need is just a modified version of a file like this https://github.com/teiid/teiid-operator/blob/master/deploy/crs/vdb_from_mongodb.yaml for Cassandra.

Ok, got it!

> Then you can consider a blog of using Teiid or Teiid Spring Boot.
What do you mean by considering a blog?

**Comment by rareddy** [comment]
> What do you mean by considering a blog?

You can write a blog how to use Cassandra with Teiid Spring Boot to showcase your work. See there are some examples as documentation (Readme.md) files in the Teiid Spring Boot repo for other data sources.

**Comment by aditya300899** [comment]
Ok!

**Pull request merged**
