### PR TITLE
TEIIDSB-211 sample, addition to util and mustache

### PR DESCRIPTION
**Pull request by aditya300899**

### CODE REVIEW

**Comment by aditya300899** [comment]
[WARNING] Found duplicate and different resources in [com.amazonaws:aws-java-sdk-swf-libraries:1.11.22, org.springframework.data:spring-data-jpa:2.2.6.RELEASE]:
[WARNING]   builddef.lst
[WARNING] Found duplicate classes/resources in compile classpath.
[WARNING] Found duplicate and different resources in [com.amazonaws:aws-java-sdk-swf-libraries:1.11.22, org.springframework.data:spring-data-jpa:2.2.6.RELEASE]:
[WARNING]   builddef.lst
[WARNING] Found duplicate classes/resources in runtime classpath.

I removed the dependency on spring-data-jpa because the build was failing on the 1st commit due to the above. I don't see why yet.

**Comment by aditya300899** [comment]
I excluded the com.amazonaws:aws-java-sdk-swf-libraries:1.11.22 from aws-sdk-java considering that we won't need it as amazon simple work flow is used to easy build some cloud applications. In my opinion, this is a better workaround. What do you think?

**Comment by shawkins** [comment]
> In my opinion, this is a better workaround. What do you think?

Once we incorporate the changes from the Teiid side we should have more targeted dependencies.

**Comment by shawkins** [comment]
Incorporated these commits into https://github.com/teiid/teiid-spring-boot/pull/278

**Pull request closed without merging**
