### PR TITLE
Added profile core-release so that infinispan is excluded, not being built in teiid for the next release

### PR DESCRIPTION
**Pull request by vhalbert**

### CODE REVIEW

**Comment by rareddy** [comment]
Why are we excluding? I thought we will include it and see if we can push this as a tech preview feature. If we exclude we can't do that. I believe we did the same in core Teiid also.

**Comment by vhalbert** [comment]
We've not got the PM's approval to make infinispan TP and build against the unreleased infinispan 10.  So teiid [](https://github.com/teiid/teiid/blob/13.0.x/connectors/pom.xml) hasn't  been changed to build infinispan.

**Comment by rareddy** [comment]
I am not asking for approval from PM, I am using a community Infinispan library in this case, that to only client driver, not any server components. We have to keep the progress up on this feature, otherwise, it is not deliverable in a single quarter. I will ask for if they approve as tech preview if we have something to show. If there nothing, nothing to ask.

**Comment by vhalbert** [comment]
Ok, I'll close this, and use the teiid master branch (13.1.0-snapshot) as the target for 7.6 release.

**Pull request closed without merging**
