### PR TITLE
Teiidsb 186

### PR DESCRIPTION
**Pull request by rareddy**

### CODE REVIEW

**Comment by rareddy** [comment]
shows the consolidation around ExternalSource removes previous ambiguity. I still have not done the consolidations in the "spring-data-xxx" yet. But this can still evolve into what you are saying, but wanted to show you where I am

**Comment by rareddy** [comment]
>Looks good. After merging with master latest I can't seem to get a clean build. Either random test >failures (probably unrelated) or dependency problems.

Built on machine multiple times, we should probably check with yours again, after I make the below changes.

>On a related note it makes things easier if Connections use pure interfaces, we should deprecate or change BaseConnection to be an interface.

I will make the change

>At this point it could make sense to move the mustache files by their respective connection >factories.

ok, will do that. This means I can remove SourceType or keep it and it will have JDBC and Custom types. At one time I was contemplating to write/generate classes with @ConnectionFactoryConfug even for the JDBC types, can still do that, but did not find much reason to do.

At this point it could make sense to move the mustache files by their respective connection factories.

> so it would not be found via the ExternalSource.find method.
my expectation is, user needs to add a dummy Connection to make it work.

> It may be better to maintain a treemap by name to avoid the linear searches.
Ok, will convert to a synchronized treemap.

BTW, what I was thinking, adding a step to Operator build to generate the json file and feed it to that. Also wondering if it is helpful to add in the connection/translator properties to the mix, so that we can validate any invalid properties in the "datasources" wdyt?

**Comment by shawkins** [comment]
> Also wondering if it is helpful to add in the connection/translator properties to the mix, so that we can validate any invalid properties in the "datasources" wdyt?

As long as that is part of the vs code effort, it sounds good.  As long as we are not dealing with xa nor pooling properties it's pretty straight-forward.

**Comment by rareddy** [comment]
@shawkins I updated with your suggestions, take a look at the last commit and please review.

**Comment by shawkins** [comment]
LGTM.  

This should make the convention based logic for the operator that I was mentioning on ENTESB-11938 a little clearer.  For each of the connection factories except for google-spreadsheets, the dependency is simply org.teiid:spring-data-name and the property prefix is similar with some inconsistency in the handling of -.

If we straighten out the inconsistency and add a org.teiid:spring-data-name module for each of ExternalSources (which would include their transitive driver dependencies) then I think we could remove all source specific dependency and property information from the operator.  The only thing we would need to do is improve how we know which dependencies to include - ideally driven off of some parsing of the ddl rather than a text search.

**Comment by rareddy** [comment]
> If we straighten out the inconsistency

Do you mean for the `google-spreadsheets`? I can rename the module, and also include a duplicate one to match new one. Did you find any others?

>add a org.teiid:spring-data-name module for each of ExternalSources 

Should be that way already, only `rest` has different property prefix but I logged as a separate ticket but we can fix here.

> I think we could remove all source specific dependency and property information from the operator.

yes, I most have changes ready on Operator to show this already, once we finalize here, I will post that changes for review

>  The only thing we would need to do is improve how we know which dependencies to include - >ideally driven off of some parsing of the ddl rather than a text search.

I added parsing based on RegEx for `CREATE SERVER` in Operator, but dependencies still driven from the Spring Boot side in the son file that gets generated. Are you suggesting, we could read dependncies from pom.xml file for `spring-data-xxx` project? I guess that could be devised

> Custom translator / sources would introduce additional concerns.

It should not IMO, as we are asking the user to list all dependencies in the YAML file along with the depency of the source connection itself.

**Comment by shawkins** [comment]
> Do you mean for the google-spreadsheets? I can rename the module, and also include a duplicate one to match new one. Did you find any others?

Yes, it's an issue with - in the name

source google-spreadsheet
module spring-data-google
prefix spring.teiid.data.google.sheets

source amazon-s3
prefix spring.teiid.data.amazon-s3

source sap-gateway
prefix spring.teiid.data.sap

> Should be that way already, only rest has different property prefix but I logged as a separate ticket but we can fix here

I don't think you follow me.  I'm saying that everything that has a ConnectionFactory with name x is ending up with a dependency org.teiid:spring-data-x and a property prefix spring.teiid.data.x.  Everything else that is represented by an ExternalSource (effectively JDBC and loopback) could as well be represented by a dependency org.teiid:spring-data-x.  The only thing that the operator would need to know is to use the default property prefix - which we could bake into the naming convention, or use things like the TYPE attribute on CREATE SERVER.

>  Are you suggesting, we could read dependncies from pom.xml file for spring-data-xxx project? I guess that could be devised

No, the operator would just need to know to include org.teiid:spring-data-x where x is driven by the server name.

**Comment by rareddy** [comment]
I will fix the `google` and `sap`, `amazon-s3` is fine

> I don't think you follow me. 

I understand. I already took that concept for the prefixes, but not for dependencies. The rationale I was thinking was since we need to do this for JDBC anyway, why not keep it consistent across both, I can make it an optional property and remove from our list, then make it work both ways.

**Comment by rareddy** [comment]
@shawkins on last time check, I fixed the google-sheets, infinispan, sap stuff. Also removed the dependencies for the all `data` projects and prefixes to default to the naming convention.

**Pull request merged**
