### PR TITLE
TEIIDSB-126 - SimpleDB Samples

### PR DESCRIPTION
**Pull request by ciphereck**
**Related Work:**
- #281 
- https://github.com/teiid/teiid-spring-boot/commit/633ce9f46b84d89cb19321a95445a2d933859529

### CODE REVIEW

**Comment by ciphereck** [comment]
[Questions]:

- Currently, when I run Application it fails, with error message
`Error creating bean with name 'simpledb': Requested bean is currently in creation: Is there an unresolvable circular reference?` 
and 
`s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'simpledb': Requested bean is currently in creation: Is there an unresolvable circular reference?`

How to resolve them?
- I think there is some issue with dependency injection, which I'm not able to identify?
- Also, I think I need simpledb locally to run this program? I installed **aws**, but I don't have secret and access key for it. Can you help here?


- Also, I'm not sure what the jdbc template is doing in almost all the samples, and how it is executing the query of select, when there is no data in dummy dbs? Can you shed some light here?

**Comment by ciphereck** [comment]
cc:
@shawkins @rareddy

**Comment by shawkins** [comment]
> I think there is some issue with dependency injection, which I'm not able to identify?

You don't need the autowired annotation on simpledb as you are supplying the bean with that method.  The error you are seeing is due to the class being name DataSource - that is making spring boot think that it is the bean to use as the java sql DataSource.  If you name that configuration class something (typically DataSources) else it will work.  Unfortunately spring can come up with pretty inscrutable error messages.

**Comment by ciphereck** [comment]
> You don't need the autowired annotation on simpledb as you are supplying the bean with that method. The error you are seeing is due to the class being name DataSource - that is making spring boot think that it is the bean to use as the java sql DataSource. If you name that configuration class something (typically DataSources) else it will work. Unfortunately spring can come up with pretty inscrutable error messages.

- Removed the autowired.
- Changed the Config class to DataSources. I didn't noticed it actually.


**[Question:]**
How to test this sample example? Like now when I run, it execute without any failure. But I think, I need an instance of simpledb to execute the select query? How to do/provide that?

**Comment by shawkins** [comment]
> Like how to create a simpledb instance locally?

I don't know of a local option.  You probably need a test instance in aws.

**Comment by ciphereck** [comment]
> I don't know of a local option. You probably need a test instance in aws.

I'm digging that for simpledb. Let me dig up some more and get back to you on this.

**Comment by ciphereck** [comment]
I tried using 
- a local SimpleDB server (like [server](https://pypi.org/project/simpledb-dev2/) or simpledb-dev3) provided by pip packages. The server started, but i wasn't able to connect the server will the Intellij execution. I tried running it on different ports like 80, 443, 8080 etc.
- Thought of using AWS console directly. But I'm not able to find simpledb services there. I think to use simpledb services, you need a paid account (not sure thought).

- No amazon simpledb service on aws web console
Screenshot 2020-07-22 at 4 01 34 PM

- No amazon simpledb service on aws terminal locally.
Screenshot 2020-07-22 at 3 56 17 PM

How to proceed now?

@shawkins @rareddy

**Comment by shawkins** [comment]
> How to proceed now?

I don't recall ever setting up an instance and it does not appear to be available in the free tier any longer.  It looks like it was deprecated a while ago and can only be accessed via the sdk https://www.reddit.com/r/aws/comments/a3280t/no_amazon_simpledb/

Dynamodb became the logical successor to simpledb, but they never officially decommissioned simpledb.

**Comment by rareddy** [comment]
maybe we can just delete the `simpledb` altogether atlease in Teiid Spring Boot? why carry a something no one can use?

**Comment by ciphereck** [comment]
So, tell me how you want me to proceed? Should I depreciate/ close this PR for now? @rareddy

**Comment by rareddy** [comment]
if dynamodb is the successor you can investigate to see (if) how much of this code be transferable to that, then if yes we can rename and convert to that, otherwise I would say let's remove it altogether not just just this PR the whole sampledb data project too

**Comment by ciphereck** [comment]
Okay, I'll investigate about it and let you know.
Also, even if dynamodb is successor, we anyways need to change the translator of simpledb in teiid-parent? Isn't it?

**Comment by rareddy** [comment]
yes, it becomes a bigger task, if there is no path forward, then we will just settle for the removal for now in Teiid Spring Boot as this never existed here before here. We will handle Teiid separately. If there is path forward then we can consider changing in both.

**Comment by ciphereck** [comment]
Got that 👍🏻 I'll try to figure out, if there's any path forward.

**Comment by ciphereck** [comment]
Sorry for late reply. I was travelling for the past two days. There was a need to visit college.

_**Continuing the above discussion:**_ 
I read about simpledb and dynamo db. 
**Summary**
Both are key value pair db, but dynamo db is a document db also. There are triggers in dynamo db but not in simpledb. Partitions in dynamo db but not in simpledb. Dynamo db follows ACID property, but simpledb not. 
As per the code, I don't think it is only sipmple naming. Because simpledb stores data in domains, like excel single worksheet and dynamo db in table.
>
>
**Question** 
You mentioned about finding any way to change simpledb to dynamodb and how much work is needed.
I want to know how to figure that out. Like what's the criteria to decide that? Maybe functions of both clients and structure of db might be a way to figure that out? Or what can be the proper way?
I'm adding links of simpledb client and dynamo db client for you to have a quick look. _Also, it will be a big help if you can tell me how to figure out whether we can change simpledb to dynamo db._

- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient.html
- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpledb/AmazonSimpleDBClient.html

**Comment by shawkins** [comment]
> I want to know how to figure that out. Like what's the criteria to decide that? 

The goal would be to use the existing simpledb logic as a starting point, but it would be a new source / translator that could be started in Teiid or Teiid Spring Boot.  The criteria to decide is mostly up to your interest level - there is support for dynamodb in various parts of jboss middleware, so it's nice to have that in Teiid is well.  If it's something you'd like to contribute we can certainly work towards that.

> Maybe functions of both clients and structure of db might be a way to figure that out? Or what can be the proper way?

Yes the apis look similar.  It doesn't look like it would take a great deal of effort to port the current logic to a new source / translator.

**Comment by ciphereck** [comment]
> The goal would be to use the existing simpledb logic as a starting point, but it would be a new source / translator that could be started in Teiid or Teiid Spring Boot. The criteria to decide is mostly up to your interest level - there is support for dynamodb in various parts of jboss middleware, so it's nice to have that in Teiid is well. If it's something you'd like to contribute we can certainly work towards that.

Well, I'm okay with contributing in that zone. It actually interests me how translator works in teiid. It will be cool to know about it.
Just some points I like to convey/ask?
- What is the expected time/ work is needed in completing this specific task? I like to have this info to better manage this, apart from my other required works commitments.
- Regarding this PR, am I supposed to close this one?
- Regarding the previous PR, are we going to create another PR for removing it, or will leave it as it as and once dynamo translator is complete, we'll update the names and packages from simpledb to dynamo?
- I might need starting pointers / some help on how to drive the translator, since I'm going to write it from scratch. I hope, this will not be a big deal? Just some sub goals with little instructions will suffice. It's because, I never worked on something like this before, but I'm really excited to take this challenge.
>
Let me know what you think on all this, or is there any other info, you like to convey?

**Comment by shawkins** [comment]
> What is the expected time/ work is needed in completing this specific task? I like to have this info to better manage this, apart from my other required works commitments.

Assuming the apis are as similar as they seem at first glance it should take about 1 week part-time to port the code and test a new source/translator.  You could guess that it won't quite be that easy and/or there would be some new type handling or other logic which could again add about 1 week part-time.

> Regarding this PR, am I supposed to close this one?

Yes, we can simply close this.

> Regarding the previous PR, are we going to create another PR for removing it, or will leave it as it as and once dynamo translator is complete, we'll update the names and packages from simpledb to dynamo?

You can leave everything that is on the Teiid side.  Before removing a source we need to mark it as deprecated and some simpledb instances are still running in aws apparently.  You could open a pr to remove simpledb from Teiid Spring Boot. 

> I might need starting pointers / some help on how to drive the translator, since I'm going to write it from scratch. I hope, this will not be a big deal? Just some sub goals with little instructions will suffice. It's because, I never worked on something like this before, but I'm really excited to take this challenge.

Hopefully it will mostly be a porting exercise.  Start by creating copies of the translator-simpledb and connector-simpledb modules and rename them dynamodb.  Make the initial focus be on dependency update and the code - the specifics related to wildfly (cli, module files, resourc adapter related) are straight-forward, but tedious, and I can help with that later.  The initial goal is to have the new modules building against the new api, then we can look for any necessary changes/improvements.

**Pull request closed without merging**
