### PR TITLE
TEIIDSB-100 moving static handling

### PR DESCRIPTION
**Pull request by shawkins**

### CODE REVIEW

**Comment by rareddy** [comment]
Looks good. Any reason to move "static" to root rather than "/odata/static"? Also, you may want to open up no security for "static" calls?

**Comment by shawkins** [comment]
>  Any reason to move "static" to root rather than "/odata/static"? 

https://issues.jboss.org/browse/TEIIDSB-100 - that was part of the reason to introduce the odata context, to move special url values out of the picture.

> Also, you may want to open up no security for "static" calls?

That handling seems a little disjointed.  There's an exclusion already in WebConfig, which implies that the auth interceptor won't be used for static.  There's also handling in the keycloak SecurityConfig to allow actuator and metadata calls.  Should that be consolidated to a single place?

**Comment by rareddy** [comment]
Yea, we need to consolidate list to one place, to avoid confusion I guess.

**Comment by shawkins** [comment]
> Yea, we need to consolidate list to one place, to avoid confusion I guess.

Do you want that as part of this pr or with a separate jira?

**Comment by shawkins** [comment]
Looking at things a bit more the behavior is a bit messy.

To make static stuff accessible it does require a change to the keycloak securityconfig.

With the KeyCloak dependency, the WebConfig / AuthenticationInterceptor simply becomes a passthrough authentication layer.  Without the KeyCloak dependency it's just creating anonymous authentications, which are allowed because trustAllLocal is true.  However an anonymous login is implicit with trust all local and no username, so we probably can just remove the AuthenticationInterceptor stuff completely.

**Comment by rareddy** [comment]
AuthenticationInterceptor was added specifically such that when keycloak is not there it is simple passthrough otherwise uses keycloak spring security. Otherwise, I have seen errors with login process. I can;t recollect exactly what they were.

**Comment by shawkins** [comment]
> Otherwise, I have seen errors with login process. I can;t recollect exactly what they were.

After the updates to the security stuff, it's not needed.

**Comment by shawkins** [comment]
Are you good to merge this?

**Comment by rareddy** [comment]
Merged it

**Pull request merged**
