### PR TITLE
TEIIDSB-224 runtime dependencies aren't available when the mojo is run

### PR DESCRIPTION
**Pull request by shawkins**

### CODE REVIEW

**Comment by shawkins** [comment]
@rareddy I recall you having some issue with Hive previously, so I wanted to let you weigh in here.  From what I'm seeing we can't use the runtime scope for driver dependencies and have a build-time check for the driver class.  They need to be compile time, or we have to remove the check.  Here I've changed to compile time dependencies, but have not started to iron out the dependency issues hive introduces yet.

**Comment by rareddy** [comment]
Sure, we should remove the `runtime` designation for dependencies for drivers, we would have to handle dependency conflicts, with hive it was many as I recall

**Comment by shawkins** [comment]
@rareddy the least messy way to handle this is to switch to the standealone hive, which is in the next commit.  It clocks in at 59MB, so that will be a good bit of overhead with builds, but it should work.

**Comment by rareddy** [comment]
Sounds good, that will work

**Pull request merged**
