### PR TITLE
ENTESB-11602: Providing a way to configure pem based key/certificate …

### PR DESCRIPTION
**Pull request by rareddy**
…to create java keystore to be used with SSL

### CODE REVIEW

**Comment by rareddy** [comment]
@shawkins I believe just like other JIRAs I logged yesterday this functionality can be taken back to core Teiid and remove the unnecessary extensions in TSB. WDYT?

**Comment by shawkins** [comment]
Which extensions do you mean?  Or do you just mean you'd rather have the pem logic in core teiid?

**Comment by rareddy** [comment]
Yes, there is nothing specific to spring boot there, we can pull in as part of embedded

**Comment by shawkins** [comment]
> Yes, there is nothing specific to spring boot there, we can pull in as part of embedded

That would be for if/when we don't use spring boot, or if someone wants to use embedded on openshift?

**Comment by rareddy** [comment]
>That would be for if/when we don't use spring boot, or if someone wants to use embedded on >openshift?

@shawkins  IMO neither specifically, just to support the PEM files directly without keystore.

**Pull request merged**
