### PR TITLE
TEIIDSB-206 adding sample for hdfs

### PR DESCRIPTION
**Pull request by aditya300899**
I Tried for a similar example as in FTP. The error shows : 
java.lang.IllegalStateException: Source type 'mysite' not supported on TextTable stock_price. Only "file","rest","amazon-s3" and "ftp" are supported
Is there something wrong that I am doing or the TextTable doesn't support files in hdfs?

### CODE REVIEW

**Comment by rareddy** [comment]
try writing example like in the vdb-example case which does not use JPA case.

**Comment by aditya300899** [comment]
I saw the vdb example! I did not quite follow what it is doing. The user function class and all...

**Comment by rareddy** [comment]
may be see this https://github.com/teiid/teiid-spring-boot/tree/master/samples/cassandra

**Comment by aditya300899** [comment]
You have linked the cassandra example. It also uses the jdbc case, i think. Isn't it?

**Comment by rareddy** [comment]
No it is not using JDBC driver, but I gave that to show how vdb based example works, in the other pattern you do not need to define an explicit VDB, it derives a VDB from sources defined. We call it JPA model, but we have not been paying much attention to that lately

**Comment by rareddy** [comment]
Thanks @aditya300899

**Pull request merged**
